Prevent TypeError
The .exec will pass and .done will fail in some instances.  done is deprecated version of exec here anyway.

Prevents:
TypeError: Object [object Object] has no method 'done'

See balderdashy/sails#1607